name: Dump
on:
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
          tags: tag:ci
          version: 1.50.1
          sha256sum: d9fe6b480fb5078f0aa57dace686898dda7e2a768884271159faa74846bfb576
      - name: Setup psql client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client        
      - name: Export PostgreSQL dump to S3
        run: |
          export PGPASSWORD=${{ secrets.DB_PASSWORD }}
          export PGUSER=${{ secrets.DB_USER }}
          export PGDATABASE=${{ secrets.DB_DATABASE }}
          export PGHOST=${{ secrets.DB_HOST }}
          pg_dump --file=dump.sql
          aws s3 cp dump.sql s3://${{ secrets.S3_BUCKET }}/${{ vars.S3_KEY }}